<div>
    @if($next)
    <x-jet-form-section submit="add">
            <x-slot name="title">
                {{ __('Continued Demo: ').(isset($demo)?$demo->name:'Null') }}
            </x-slot>

            <x-slot name="description">
                {{ __('File Upload Fields Generated by examing the input file') }}
            </x-slot>

            <x-slot name="form">
                @if(isset($input_files))
                    @foreach($uploadFields as $fileType => $extension)
                        <div class="col-span-6 sm:col-span-full">
                            <x-jet-label class="mt-5" for="{{'input_files.'.$fileType}}" value="{{  'Input '.$fileType.' File'  }}" />
                            <x-jet-input id="{{'input_files.'.$fileType}}" type="file" class="mt-1 block w-full" wire:model="input_files.{{$fileType}}" enctype='multipart/form-data' accept="{{'.'.$extension}}"/>
                            <div class="text-black-500" wire:loading wire:target="input_files.{{$fileType}}">Uploading...</div>
                            <x-jet-input-error for="input_files.{{$fileType}}" class="mt-2" />
                        </div>
                    @endforeach
                @endif


                <div class="col-span-6 sm:col-span-full">
                    <x-jet-label class="mt-5" for="output_files" value="{{ __('Output Files (select multiple files)') }}" />
                    <x-jet-input id="output_files" type="file" class="mt-1 block w-full" wire:model="output_files" enctype='multipart/form-data' multiple/>
                    <div class="text-black-500" wire:loading wire:target="output_files">Uploading Multiple Files...</div>
                    <x-jet-input-error for="output_files.*" class="mt-2" />
                </div>

                <div class="col-span-6 sm:col-span-full">
                    @foreach($output_file_names as $output_file_name)
                        <x-jet-label value="{{ $output_file_name }}" /> 
                    @endforeach
                </div>

                <div class="col-span-6 sm:col-span-full">
                    <x-jet-label class="mt-5" for="plotFile" value="{{ __('Plot Image File (max:10MB)') }}" />
                    <x-jet-input id="plotFile" type="file" class="mt-1 block w-full" wire:model="plotFile" enctype='multipart/form-data' accept='.jpg,.jpeg,.png,.gif'/>
                    <div class="text-black-500" wire:loading wire:target="plotFile">Uploading Image...</div>
                    <x-jet-input-error for="plotFile" class="mt-2" />
                </div>

                <div class="col-span-6 sm:col-span-full">
                    @if(isset($plotFile))
                        <x-jet-label class="my-5" for="plot_image" value="{{ __('Plot Image: ').$plotFile->getClientOriginalName() }}" />
                        <img id="plot_image" src="{{ $plotFile->temporaryUrl() }}" alt="Something Wrong to Display Image">
                    @endif
                </div>



                <div class="col-span-6 sm:col-span-6">
                    <x-jet-label for="fld-status" value="{{ __('Display') }}" />
                    <select id="fld-status" wire:model.defer="status" {{ $displayEditable ? "" : "disabled" }} class="mt-1 block w-full textarea border-gray-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-lg">
                        <option value="1">Yes</option>
                        <option value="0">No</option>
                    </select>
                    <x-jet-input-error for="status" class="mt-2" />
                </div>

            </x-slot>

            <x-slot name="actions">
                <x-jet-button class="btn-submit-form-has-tinymce">
                    {{ __('Create') }}
                </x-jet-button>
            </x-slot>
        </x-jet-form-section>
    @else
        <x-jet-form-section submit="registerDemo">
            <x-slot name="title">
                {{ __('New Demo') }}
            </x-slot>

            <x-slot name="description">
                {{ __('Add a new demo for get_started.') }}
            </x-slot>

            <x-slot name="form">
                <div class="col-span-6">
                    <x-jet-label value="{{ __('New Demo') }}" />
                </div>

                <div class="col-span-6 sm:col-span-3">
                    <x-jet-label for="name" value="{{ __('Name') }}" />
                    <x-jet-input id="name" type="text" class="mt-1 block w-full" wire:model.defer="name" />
                    <x-jet-input-error for="name" class="mt-2" />
                </div>

                <div class="col-span-6 sm:col-span-3">
                    <x-jet-label for="category_id" value="{{ __('Category') }}" />
                    <select
                        class="block mt-1 w-full textarea border-gray-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-lg" id="category_id"
                        wire:model.defer="category_id">
                        @foreach($categories as $key => $value)
                            <option value="{{$key}}">{{$value}}</option>
                        @endforeach
                    </select> 
                    <x-jet-input-error for="category_id" class="mt-2" />
                </div>

                <div class="col-span-6">
                    <x-jet-label for="description" value="{{ __('Description') }}" />

                    <textarea
                        name="description"
                        class="mt-1 block w-full textarea border-gray-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-lg" 
                        rows="6"
                        wire:model.defer="description">
                    </textarea>

                    <x-jet-input-error for="description" class="mt-2" />
                </div>

                

                <div class="col-span-6 sm:col-span-full">
                    <x-jet-label for="input_file" value="{{ __('Input File') }}" />
                    <x-jet-input id="input_file" type="file" class="mt-1 block w-full" wire:model="input_file" enctype='multipart/form-data' accept='.input' required/>
                    <div class="text-black-500" wire:loading wire:target="input_file">Uploading...</div>
                    <x-jet-input-error for="input_file" class="mt-2" />
                </div>

            </x-slot>

            <x-slot name="actions">
                <x-jet-button class="btn-submit-form-has-tinymce">
                    {{ __('Next') }}
                </x-jet-button>
            </x-slot>
        </x-jet-form-section>
    @endif
</div>
